### ISSUE TITLE
Minus koordinaten / Minus coordinates

### ISSUE THREAD

**Issue by BizzWareX** [Voiture-0/PlaceTemplater#2]
Hallo leider gehen keine Minus koordinaten, diese wären aber notwendig für r/place 2023

Hello unfortunately no minus coordinates work, but these would be necessary for r/place 2023

**Comment by Visne** [comment]
Would already be fixed by #1, but maintainer is inactive. You can deal with it by changing the `min="0"` value with browser debug tools.

**Comment by Visne** [comment]
Actually it seems like they already fixed it, just left my PR open.

**Comment by Voiture-0** [comment]
Fixed with ee450ca
